name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        uses: docker://kremi151/android-sdk:android-28
        with:
          entrypoint: ./.github/workflows/scripts/build.sh
      - name: Change ownership of build directory
        run: sudo chown -R $(id -u):$(id -g) ${{ github.workspace }}/app/build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: 3D-Tic-Tac-Toe
          path: |
            ${{ github.workspace }}/app/build/outputs/apk/release/*.apk
